data:
  image: "mnel/data"
  volumes: ["./:/app:rw"]

phpfpm:
  build: "."
  dockerfile: ".docker/phpfpm/Dockerfile"
  restart: "always"
  volumes: ["./.docker/phpfpm/php.ini:/usr/local/etc/php/php.ini"]
  volumes_from: ["data"]
  environment:
    APP_ENV: local
    APP_DEBUG: "true"
    APP_KEY: XCVVASDQASDsdsdsdgesdjyhttyhfghf
    JWT_PRIV_KEY: |
      -----BEGIN PRIVATE KEY-----
      MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC5bQdnu6bd79i1
      xwuE3P5hZaSAMDhFcIXPVApwqQm/1Xpm+YoYDZMmtmDH9GQnAkulu8n1LTmRiNje
      ZwWJmehleODeL6RRYdZU2p2Mx+rtR4cpTgrCtnv8vJGAZSoMvjP7je8om3SMzCiR
      LajE1/CgJ6xsILkxzrk7lwznC9qSTU96n7P5TanEtvrQsXfSt5jX1gdWCpdMXim8
      hURInMmoNpO9k3avIFlhSU3vOXumTVgd1eZL9xeG+jBpgwL11CmXHNoo3JW1Wm+l
      lB7z716HDIWp55SoOKVxTjnwoNP6H6t2ivfhSoBo43m+4l1/AZegLwQf1T9vcLf9
      5IAzshzrAgMBAAECggEAEiFe//2RK1IwVlXIAo25MbzGgOI2HlQKQWNuQeXFVkSB
      W2A66G8rXDWo8OQshsPqsaHS9W4emuROkDBykinCV2miUxdFcc+nLVTS4tkJV3oO
      9TL0SmWdafDmKS+7FNPkMUyHfej1VG8B6HAWeGjE1mQKr+fjM8OKyRDT6iN2k6dg
      2gNTiIxejaaO2i9NoANT/g5KvrMA/PmzB1+OP3oMfBZi8TY0p62QmO6WSq4+Vnnt
      WxYAqDkEwSXcOgHtHnf4Ah0EiyZSp2GHIE29/H6m5k8ynlwvykTlbXPcOX8LQ7oK
      betkCi2lFyZNw26gRHubSCnhgtZH4JkxkhwtorvJQQKBgQDmSjfa/5sJps4v7UA/
      GITTQ69xOUEc1SLZDJRsnfcTja49LcrMc9gX2u3GiHs1/j8IHKLBTzQ5YsMt78OG
      +GF/m7smbQ8NSoHBwRfHP+hinz8U+VRiA8VJmbKxoeFupBGYYFxVsMIqL7LvcOVj
      OlKqMHyqvYkjVWXOH1qpRqV/pwKBgQDOIJQM6lxehJ3TfOyYULEsb04vUkAQCiP7
      80Xzgq918DsImF4A7YfYb7LPlJWkY6ab3ox7q4QG9rommIDgpf5j6AE8hBPuyACw
      YEvU5bMc8hsQ6DuzgMmpuxyVhE9YcQJSsFESd2qkp1Dxd1xj7o5Wbyu6/kVKK0Ie
      Jtuq3VUBHQKBgDaes9DFf0gywASuCObuMdLJ4vq/0am9A57nVOzOKqQAnqr0CX2k
      nERMMMk95btQqjKKWC/xUTmrKw/iJkYE81sI3MKoa0GDwnLqEXG4vq1lh9i5qkH1
      Ev357mAjPQy47VNux3erjOHknlQcOsvmMWUcSvVULwqqXpMc7KvpjadRAoGAM6nC
      scIDyMTgceN7wWloHsT/CalJ2TtRbZK506DLrXm6shrOZNkkFUFZxeFt6Df5yFNt
      Toncm4o3efj7RFMWgZ/iv3IzNMP4ODzKhN/VlsmvsvsiC4maAeqd7XOuF3KrrGH4
      z/ISTpaJGRxbkch28H8IrOOSJlbVSY1fvWGgLpkCgYAbCwp7aPvSZsBFsNltLGnw
      /6HR8GbSNYP+7edc1RieEV+jhaIucHTtc+7TRdFC9AAsuF+nLRFyQMGa5rmDt4zs
      d/3in+LCKKdjozdRBU5G5HuKGaPQ+3/47SUr34Ck7kfeOMmLcR8i9d201Ca2r4NL
      ufrXLm0pK46LXndPEonR5w==
      -----END PRIVATE KEY-----
    JWT_PUB_KEY: |
      -----BEGIN CERTIFICATE-----
      MIIDXTCCAkWgAwIBAgIJAPtw7/nnD7g2MA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
      BAYTAlpBMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
      aWRnaXRzIFB0eSBMdGQwHhcNMTcwNTMxMDc1MDQxWhcNMTcwNjMwMDc1MDQxWjBF
      MQswCQYDVQQGEwJaQTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50
      ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
      CgKCAQEAuW0HZ7um3e/YtccLhNz+YWWkgDA4RXCFz1QKcKkJv9V6ZvmKGA2TJrZg
      x/RkJwJLpbvJ9S05kYjY3mcFiZnoZXjg3i+kUWHWVNqdjMfq7UeHKU4KwrZ7/LyR
      gGUqDL4z+43vKJt0jMwokS2oxNfwoCesbCC5Mc65O5cM5wvakk1Pep+z+U2pxLb6
      0LF30reY19YHVgqXTF4pvIVESJzJqDaTvZN2ryBZYUlN7zl7pk1YHdXmS/cXhvow
      aYMC9dQplxzaKNyVtVpvpZQe8+9ehwyFqeeUqDilcU458KDT+h+rdor34UqAaON5
      vuJdfwGXoC8EH9U/b3C3/eSAM7Ic6wIDAQABo1AwTjAdBgNVHQ4EFgQUZ08XAxB8
      1Vmuud2ySs/4DCxqwq4wHwYDVR0jBBgwFoAUZ08XAxB81Vmuud2ySs/4DCxqwq4w
      DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAHrObSI1Ad4r2m+E5kBOp
      HCF3EZaksGXUHZYCR7q7gLWLhxIB5DRoc+p9y/Yn1N5m12EOu2D31AC6dPbwbiZn
      0jlZSO8nwdpVtlYq7EvOvLh5KakUy49mpExfPiDnZlXgmiFm4Vb1j7SBaIgT7pC6
      YSy37Y8t6oPw0e9JyXuu6ACT0QkR0vYbrzYu5NKnIB4IGDH/1f2YHOov++hd357c
      w9t/XycrBEiXMV11IvCAXRUNKtetNRkrVsfw9PSBkCRhlzy7DdUX5N0t1l17URXh
      gyyW4VP0VQx+hn0slMuMfWzT9DiV5W3a135r2sHFUqkVZcWt++6xun1yk5RtGmvk
      Nw==
      -----END CERTIFICATE-----
    CACHE_DRIVER: array
    QUEUE_DRIVER: sync

web:
  image: "nginx:1.11.5"
  restart: "always"
  command: "nginx -c /app/.docker/nginx/nginx.conf"
  links: ["phpfpm"]
  volumes_from: ["data"]
  environment:
    VIRTUAL_HOST: "lumen_jwt"
    HTTPS_METHOD: "noredirect"